name: Manual workflow

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]

permissions:
  id-token: write
  contents: read


jobs:
  codebuild:
    if: ${{ (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'bug') || github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.action != 'labeled') }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2
